capitals = {"Saint Lucia": "Castries",
            "Saint Vincent and the Grenadines": "Kingstown",
            "Samoa": "Apia",
            "San Marino": "San Marino",
            "Saudi Arabia": "Riyadh",
            "Senegal": "Dakar",
            "Serbia": "Belgrade",
            "Seychelles": "Victoria",
            "Sierra Leone": "Freetown",
            "Singapore": "Singapore",
            "Slovakia": "Bratislava",
            "Slovenia": "Ljubljana",
            "Solomon Islands": "Honiara",
            "Somalia": "Mogadishu",
            "South Korea": "Seoul",
            "South Sudan": "Juba",
            "Spain": "Madrid",
            "Sri Lanka": "Sri Jayawardenepura Kotte",
            "Sudan": "Khartoum",
            "Sweden": "Stockholm",
            "Switzerland": "Bern",
            "Syria": "Damascus"}
